# Generated by Django 4.0.6 on 2022-12-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=1000)),
                ('receiver', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('friends', models.JSONField(verbose_name=models.CharField(max_length=150))),
            ],
        ),
    ]
